
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AnimatedBorder: typeof import("../app/components/AnimatedBorder.vue")['default']
export const BackToTop: typeof import("../app/components/BackToTop.vue")['default']
export const Card3D: typeof import("../app/components/Card3D.vue")['default']
export const CursorTrail: typeof import("../app/components/CursorTrail.vue")['default']
export const CustomCursor: typeof import("../app/components/CustomCursor.vue")['default']
export const Floating3DObjects: typeof import("../app/components/Floating3DObjects.vue")['default']
export const FloatingBadge: typeof import("../app/components/FloatingBadge.vue")['default']
export const Footer: typeof import("../app/components/Footer.vue")['default']
export const GlowingParticles: typeof import("../app/components/GlowingParticles.vue")['default']
export const LoadingScreen: typeof import("../app/components/LoadingScreen.vue")['default']
export const Navigation: typeof import("../app/components/Navigation.vue")['default']
export const ProjectCarousel: typeof import("../app/components/ProjectCarousel.vue")['default']
export const ScrollProgress: typeof import("../app/components/ScrollProgress.vue")['default']
export const Section3DObject: typeof import("../app/components/Section3DObject.vue")['default']
export const SectionReveal: typeof import("../app/components/SectionReveal.vue")['default']
export const SpotlightEffect: typeof import("../app/components/SpotlightEffect.vue")['default']
export const TextReveal3D: typeof import("../app/components/TextReveal3D.vue")['default']
export const ThreeBackground: typeof import("../app/components/ThreeBackground.vue")['default']
export const SectionsAboutSection: typeof import("../app/components/sections/AboutSection.vue")['default']
export const SectionsContactSection: typeof import("../app/components/sections/ContactSection.vue")['default']
export const SectionsHeroSection: typeof import("../app/components/sections/HeroSection.vue")['default']
export const SectionsProjectsSection: typeof import("../app/components/sections/ProjectsSection.vue")['default']
export const SectionsSkillsSection: typeof import("../app/components/sections/SkillsSection.vue")['default']
export const SectionsTestimonialsSection: typeof import("../app/components/sections/TestimonialsSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AspectRatio: typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']
export const Badge: typeof import("../app/components/ui/badge/index")['Badge']
export const Button: typeof import("../app/components/ui/button/index")['Button']
export const Card: typeof import("../app/components/ui/card/index")['Card']
export const CardAction: typeof import("../app/components/ui/card/index")['CardAction']
export const CardContent: typeof import("../app/components/ui/card/index")['CardContent']
export const CardDescription: typeof import("../app/components/ui/card/index")['CardDescription']
export const CardFooter: typeof import("../app/components/ui/card/index")['CardFooter']
export const CardHeader: typeof import("../app/components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../app/components/ui/card/index")['CardTitle']
export const Carousel: typeof import("../app/components/ui/carousel/index")['Carousel']
export const CarouselContent: typeof import("../app/components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../app/components/ui/carousel/index")['CarouselItem']
export const CarouselNext: typeof import("../app/components/ui/carousel/index")['CarouselNext']
export const CarouselPrevious: typeof import("../app/components/ui/carousel/index")['CarouselPrevious']
export const CarouselApi: typeof import("../app/components/ui/carousel/index")['CarouselApi']
export const Dialog: typeof import("../app/components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../app/components/ui/dialog/index")['DialogClose']
export const DialogContent: typeof import("../app/components/ui/dialog/index")['DialogContent']
export const DialogDescription: typeof import("../app/components/ui/dialog/index")['DialogDescription']
export const DialogFooter: typeof import("../app/components/ui/dialog/index")['DialogFooter']
export const DialogHeader: typeof import("../app/components/ui/dialog/index")['DialogHeader']
export const DialogOverlay: typeof import("../app/components/ui/dialog/index")['DialogOverlay']
export const DialogScrollContent: typeof import("../app/components/ui/dialog/index")['DialogScrollContent']
export const DialogTitle: typeof import("../app/components/ui/dialog/index")['DialogTitle']
export const DialogTrigger: typeof import("../app/components/ui/dialog/index")['DialogTrigger']
export const DropdownMenu: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuCheckboxItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuLabel: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuRadioGroup: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuRadioItem: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuSeparator: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuShortcut: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSub: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubContent: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const DropdownMenuSubTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuTrigger: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuPortal: typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const Separator: typeof import("../app/components/ui/separator/index")['Separator']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAnimatedBorder: LazyComponent<typeof import("../app/components/AnimatedBorder.vue")['default']>
export const LazyBackToTop: LazyComponent<typeof import("../app/components/BackToTop.vue")['default']>
export const LazyCard3D: LazyComponent<typeof import("../app/components/Card3D.vue")['default']>
export const LazyCursorTrail: LazyComponent<typeof import("../app/components/CursorTrail.vue")['default']>
export const LazyCustomCursor: LazyComponent<typeof import("../app/components/CustomCursor.vue")['default']>
export const LazyFloating3DObjects: LazyComponent<typeof import("../app/components/Floating3DObjects.vue")['default']>
export const LazyFloatingBadge: LazyComponent<typeof import("../app/components/FloatingBadge.vue")['default']>
export const LazyFooter: LazyComponent<typeof import("../app/components/Footer.vue")['default']>
export const LazyGlowingParticles: LazyComponent<typeof import("../app/components/GlowingParticles.vue")['default']>
export const LazyLoadingScreen: LazyComponent<typeof import("../app/components/LoadingScreen.vue")['default']>
export const LazyNavigation: LazyComponent<typeof import("../app/components/Navigation.vue")['default']>
export const LazyProjectCarousel: LazyComponent<typeof import("../app/components/ProjectCarousel.vue")['default']>
export const LazyScrollProgress: LazyComponent<typeof import("../app/components/ScrollProgress.vue")['default']>
export const LazySection3DObject: LazyComponent<typeof import("../app/components/Section3DObject.vue")['default']>
export const LazySectionReveal: LazyComponent<typeof import("../app/components/SectionReveal.vue")['default']>
export const LazySpotlightEffect: LazyComponent<typeof import("../app/components/SpotlightEffect.vue")['default']>
export const LazyTextReveal3D: LazyComponent<typeof import("../app/components/TextReveal3D.vue")['default']>
export const LazyThreeBackground: LazyComponent<typeof import("../app/components/ThreeBackground.vue")['default']>
export const LazySectionsAboutSection: LazyComponent<typeof import("../app/components/sections/AboutSection.vue")['default']>
export const LazySectionsContactSection: LazyComponent<typeof import("../app/components/sections/ContactSection.vue")['default']>
export const LazySectionsHeroSection: LazyComponent<typeof import("../app/components/sections/HeroSection.vue")['default']>
export const LazySectionsProjectsSection: LazyComponent<typeof import("../app/components/sections/ProjectsSection.vue")['default']>
export const LazySectionsSkillsSection: LazyComponent<typeof import("../app/components/sections/SkillsSection.vue")['default']>
export const LazySectionsTestimonialsSection: LazyComponent<typeof import("../app/components/sections/TestimonialsSection.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAspectRatio: LazyComponent<typeof import("../app/components/ui/aspect-ratio/index")['AspectRatio']>
export const LazyBadge: LazyComponent<typeof import("../app/components/ui/badge/index")['Badge']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/button/index")['Button']>
export const LazyCard: LazyComponent<typeof import("../app/components/ui/card/index")['Card']>
export const LazyCardAction: LazyComponent<typeof import("../app/components/ui/card/index")['CardAction']>
export const LazyCardContent: LazyComponent<typeof import("../app/components/ui/card/index")['CardContent']>
export const LazyCardDescription: LazyComponent<typeof import("../app/components/ui/card/index")['CardDescription']>
export const LazyCardFooter: LazyComponent<typeof import("../app/components/ui/card/index")['CardFooter']>
export const LazyCardHeader: LazyComponent<typeof import("../app/components/ui/card/index")['CardHeader']>
export const LazyCardTitle: LazyComponent<typeof import("../app/components/ui/card/index")['CardTitle']>
export const LazyCarousel: LazyComponent<typeof import("../app/components/ui/carousel/index")['Carousel']>
export const LazyCarouselContent: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselContent']>
export const LazyCarouselItem: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselItem']>
export const LazyCarouselNext: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselNext']>
export const LazyCarouselPrevious: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselPrevious']>
export const LazyCarouselApi: LazyComponent<typeof import("../app/components/ui/carousel/index")['CarouselApi']>
export const LazyDialog: LazyComponent<typeof import("../app/components/ui/dialog/index")['Dialog']>
export const LazyDialogClose: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogClose']>
export const LazyDialogContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogContent']>
export const LazyDialogDescription: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogDescription']>
export const LazyDialogFooter: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogFooter']>
export const LazyDialogHeader: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogHeader']>
export const LazyDialogOverlay: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogOverlay']>
export const LazyDialogScrollContent: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogScrollContent']>
export const LazyDialogTitle: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTitle']>
export const LazyDialogTrigger: LazyComponent<typeof import("../app/components/ui/dialog/index")['DialogTrigger']>
export const LazyDropdownMenu: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenu']>
export const LazyDropdownMenuCheckboxItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']>
export const LazyDropdownMenuContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuContent']>
export const LazyDropdownMenuGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuGroup']>
export const LazyDropdownMenuItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuItem']>
export const LazyDropdownMenuLabel: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuLabel']>
export const LazyDropdownMenuRadioGroup: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']>
export const LazyDropdownMenuRadioItem: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuRadioItem']>
export const LazyDropdownMenuSeparator: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSeparator']>
export const LazyDropdownMenuShortcut: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuShortcut']>
export const LazyDropdownMenuSub: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSub']>
export const LazyDropdownMenuSubContent: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubContent']>
export const LazyDropdownMenuSubTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']>
export const LazyDropdownMenuTrigger: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuTrigger']>
export const LazyDropdownMenuPortal: LazyComponent<typeof import("../app/components/ui/dropdown-menu/index")['DropdownMenuPortal']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/separator/index")['Separator']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
